---

- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - base
    - shell
    - tmux
    - asdf
    - dotfiles
    - vimfiles
    - ruby
    - erlang
    - role: erlang
      environment:
        KERL_CONFIGURE_OPTION: --without-javac
        KERL_USE_AUTOCONF: "yes"
    - elixir
    - golang
    - rust
    - nodejs
    - python
    - docker
