#!/usr/bin/env bash
#
# Sets up requirements to provision with ansible
#

#
# Clean display function
#
# usage:
#        display "My thing to output"
#
function display() {
    echo "----> $1"
}

if [ ! `which brew` ]; then
    display "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

PATH=/usr/local/bin:$PATH
PATH=/opt/homebrew/bin:$PATH
brew_prefix=`/opt/homebrew/bin/brew --prefix`
if [ ! `which python3 | grep -E "^${brew_prefix}"` ]; then
  display "Installing python3 from homebrew"
  brew install python@3
fi

PATH=/usr/local/opt/python/libexec/bin:$PATH
if [ ! `which pip` ]; then
    display "Installing pip"
    python3 -m ensurepip --upgrade --user
    pip3 install --upgrade pip
fi

PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"
brew install pkg-config libffi
pip3 install --user --upgrade -r requirements.txt


# vim: ft=sh:
