#!/usr/bin/env bash
#
# Sets up requirements to provision with ansible
#

#
# Clean display function
#
# usage:
#        display "My thing to output"
#
function display() {
    echo "----> $1"
}

if [ ! `which brew` ]; then
    display "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

PATH=/usr/local/bin:$PATH
brew_prefix=`/usr/local/bin/brew --prefix`
if [ ! `which python3 | grep -E "^${brew_prefix}"` ]; then
  brew install python@3
fi

PATH=/usr/local/opt/python/libexec/bin:$PATH
if [ ! `which pip` ]; then
    display "Installing pip"
    easy_install pip
fi

pip install --user --upgrade -r requirements.txt


# vim: ft=sh:
