---

- name: Install updated docker brew cask applications
  command: "brew install {{ item.force | default('') }} {{ item.name }}"
  with_items: "{{ docker_brew_cask_apps }}"
  tags:
    - brew
    - brew-cask
    - brew-cask-updates
    - docker

- name: Install docker homebrew packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ docker_brew_packages | default([]) }}"
  tags:
    - brew
    - docker
